//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altairis.VtipBaze.WebCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailerTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailerTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altairis.VtipBaze.WebCore.Resources.MailerTemplates", typeof(MailerTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///--
        ///VtipBáze - www.vtipbaze.cz.
        /// </summary>
        public static string _BodyFormat {
            get {
                return ResourceManager.GetString("_BodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [www.vtipbaze.cz] {0}.
        /// </summary>
        public static string _SubjectFormat {
            get {
                return ResourceManager.GetString("_SubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrý den,
        ///
        ///do VtipBáze byl přidáno nový vtip ke schválení. Schválit nebo smazat ho můžete na následující adrese:
        ///
        ///{0}
        ///
        ///#
        ///
        ///{1}.
        /// </summary>
        public static string JokeToApproveBody {
            get {
                return ResourceManager.GetString("JokeToApproveBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vtip ke schválení.
        /// </summary>
        public static string JokeToApproveSubject {
            get {
                return ResourceManager.GetString("JokeToApproveSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}
        ///
        ///Poznámka: Tuto zprávu dostáváte, protože jste přihlášeni do mailing listu &quot;{3}&quot;. Můžete se odhlásit na http://www.vtipbaze.cz/mailing/..
        /// </summary>
        public static string ListMessageBody {
            get {
                return ResourceManager.GetString("ListMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{2}] {0}.
        /// </summary>
        public static string ListMessageSubject {
            get {
                return ResourceManager.GetString("ListMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrý den,
        ///
        ///někdo (nejspíš vy) žádal, aby byla tato e-mailová adresa ({0}) odstraněna z mailing listu &quot;{3}&quot;. Pokud s tím souhlasíte, přejděte prosím na následující adresu (celá musí být na jednom řádku):
        ///http://www.vtipbaze.cz/mailing/remove/{0}/{1}
        ///
        ///Pokud s odstraněním nesouhlasíte, stačí tuto zprávu ignorovat..
        /// </summary>
        public static string ListRemovalVerificationBody {
            get {
                return ResourceManager.GetString("ListRemovalVerificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{2}] Potvrďte své odhlášení z mailing listu &quot;{3}&quot;.
        /// </summary>
        public static string ListRemovalVerificationSubject {
            get {
                return ResourceManager.GetString("ListRemovalVerificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrý den,
        ///
        ///někdo (nejspíš vy) žádal, aby byla tato e-mailová adresa ({0}) přidána do mailing listu &quot;{3}&quot;. Pokud s tím souhlasíte, přejděte prosím na následující adresu (celá musí být na jednom řádku):
        ///http://www.vtipbaze.cz/mailing/confirm/{0}/{1}
        ///
        ///Pokud s přidáním nesouhlasíte, stačí tuto zprávu ignorovat..
        /// </summary>
        public static string ListSubscriptionVerificationBody {
            get {
                return ResourceManager.GetString("ListSubscriptionVerificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{2}] Potvrďte své přihlášení do mailing listu &quot;{3}&quot;.
        /// </summary>
        public static string ListSubscriptionVerificationSubject {
            get {
                return ResourceManager.GetString("ListSubscriptionVerificationSubject", resourceCulture);
            }
        }
    }
}
