<%@ Page Title="VtipBáze" Language="C#" MasterPageFile="~/Pages/Site.Master" AutoEventWireup="true" CodeBehind="HomePage.aspx.cs" Inherits="Altairis.VtipBaze.WebCore.Pages.HomePage" ViewStateMode="Disabled" %>
<asp:Content runat="server" ContentPlaceHolderID="MainCPH">
    <asp:PlaceHolder ID="WelcomePlaceHolder" runat="server" Visible="false">
        <article>
            <header>
                Welcome at VtipBáze.cz
            </header>
            <p>VtipBáze is a database of jokes. These jokes were kindly generated by ChatGPT or submitted by the community.</p>
            <p>If you can't find your favorite one here, <a href="/new">add it</a>.</p>
        </article>
    </asp:PlaceHolder>
    <asp:ListView ID="JokesList" runat="server" ItemType="Altairis.VtipBaze.Data.Joke" SelectMethod="SelectJokes" OnItemCommand="JokesList_ItemCommand">
        <EmptyDataTemplate>
            <article>
                <header>Error</header>
                <p>
                    No jokes found in this category.
                </p>
            </article>
        </EmptyDataTemplate>
        <ItemTemplate>
            <article id="<%# "j" + Item.JokeId %>">
                <header>
                    <asp:HyperLink runat="server" CssClass="id" Text="<%# Item.JokeId %>" NavigateUrl='<%# this.GetRouteUrl("SingleJoke", new { JokeId = Item.JokeId })%>' />
                    <asp:Literal Text="<%# Item.DateCreated %>" runat="server" />
                </header>
                <asp:Panel runat="server" CssClass="ui-widget-content ui-state-highlight ui-corner-all" Style="padding: .5ex 1ex; margin-bottom: 1ex;" Visible="<%# !Item.Approved %>">
                    <asp:LinkButton Text="[approve]" ToolTip="Approve joke" runat="server" CssClass="ui-icon ui-icon-check" CommandName="Approve" CommandArgument="<%# Item.JokeId %>" />
                    <asp:LinkButton Text="[reject]" ToolTip="Reject joke" runat="server" CssClass="ui-icon ui-icon-closethick" CommandName="Reject" CommandArgument="<%# Item.JokeId %>" data-confirmprompt="Do you really want to delete this joke?" />
                    This joke was not approved yet.
                </asp:Panel>
                <%#: Item.Text %>
                <aside>
                    <asp:Panel runat="server" DefaultButton="AddTagButton" Style="float: right" Visible="<%# this.Request.IsAuthenticated %>">
                        <asp:TextBox ID="TextBoxNewTag" runat="server" Width="120px" CssClass="textbox ac-tag" />
                        <asp:LinkButton ID="AddTagButton" runat="server" Text="[add]" ToolTip="Add tag" CommandName="AddTag" CommandArgument="<%# Item.JokeId %>" CssClass="ui-icon ui-icon-circle-plus" />
                        <asp:LinkButton runat="server" Text="[clear all]" ToolTip="Clear all tags" CommandName="ClearTags" CommandArgument="<%# Item.JokeId %>" CssClass="ui-icon ui-icon-circle-close" data-confirmprompt="Do you really want to clear all tags from this joke?" />
                    </asp:Panel>
                    <asp:ListView runat="server" DataSource="<%# Item.Tags %>" ItemType="Altairis.VtipBaze.Data.Tag">
                        <LayoutTemplate>
                            <ul class="taglist">
                                <asp:PlaceHolder runat="server" ID="ItemPlaceHolder" />
                            </ul>
                        </LayoutTemplate>
                        <ItemTemplate>
                            <li><span class="ui-icon ui-icon-tag"></span>
                                <asp:HyperLink runat="server" Text="<%# Item.TagName %>" NavigateUrl='<%# this.GetRouteUrl("TagSearch", new { TagName = Item.TagName, PageIndex = "1" }) %>' />
                            </li>
                        </ItemTemplate>
                    </asp:ListView>
                </aside>
            </article>
        </ItemTemplate>
    </asp:ListView>
    <asp:Panel ID="PagingPanel" runat="server" CssClass="paging">
        <div style="float: left">
            <asp:HyperLink ID="PageFirst" runat="server" Text="&lt;&lt; first" />
            <asp:HyperLink ID="PagePrev" runat="server" Text="&lt; previous" />
        </div>
        <asp:HyperLink ID="PageNext" runat="server" Text="next &gt;" />
        <asp:HyperLink ID="PageLast" runat="server" Text="last &gt;&gt;" />
    </asp:Panel>
    <altairis:DataPagerExtender runat="server" TargetControlID="JokesList" PageSize="5" FirstLinkID="PageFirst" LastLinkID="PageLast" NextLinkID="PageNext" PreviousLinkID="PagePrev" InactiveLinkMode="Disable" />
</asp:Content>
